<CalendarScreen>:
    orientation:"vertical"

    BoxLayout:
        size_hint_y:.2
        canvas.before:
            Color:
                rgba:utils.get_color_from_hex('#cc7518')
            Rectangle:
                size:self.size
                pos:self.pos
        Label:
            text:"Calendar"
            font_size:"70sp"
    BoxLayout:
        orientation: 'vertical'
		Select:

        Status:



